### ISSUE TITLE
스타트 버튼이 안눌러집니다,

### ISSUE THREAD

**Issue by bomegaul** [lazygyu/roulette#11]
ui업뎃하시고나서 스타트버튼이 안눌러집니다.
이슈 확인 부탁드려요 ㅎㅎㅎ

언제나 잘쓰고있습니다 화이팅하세요!!

**Comment by yunjin-kim** [comment]
@lazygyu gtag 함수 선언이 누락된 것 같습니다!

**Comment by lazygyu** [comment]
close by #13
